id: I1A4EE4E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T19:31:32+00:00'
last_modified: '2022-06-08T04:52:51.226769+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23221
  title: རིན་ཆེན་རྒྱུད་མངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5FD0:
      image_group_id: I1KG23318
      title: ''
      total_pages: 442
      order: 1
      base_file: 5FD0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
