id: P005554
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG23221
  title: རིན་ཆེན་རྒྱུད་མངས།
  author: ''
  volumes:
    9d0283e0399c49cab32b3c6d6ddf7d86:
      image_group_id: I1KG23318
      title: ''
      volume_number: 1
      total_pages: 442
      base_file: v001.txt
